### ISSUE TITLE
Get the scraper to dump data into a folder using the Node FS API

### ISSUE THREAD

**Issue by serapath** [ethereum-play/etherscan-scraper#2]
## `@todo`
* [ ] **store scraped data**
    1. [ ] 1. store all contracts in filesystem instead of mysql
    2. [ ] 2. transform source code by replacing all `import <path/to/file>` statements in a source file with `import <hash of imported transformed source code>` 
        * **see next comment below**
    3. [ ] 3. store each contract in a folder named the hash of the contracts source code
    4. [ ] 4. store transformed source code and additional metadata and list of deploy addresses in that folder
    5. [ ] (check out https://unwalled.garden)
* [ ] **share/publish scraped data**
    * [ ] `dat share` the folder of stored contracts using the the **[dat cli](https://www.npmjs.com/package/dat)**
    * [ ] test success by loading the published dat address in beaker browser

---

**Comment by serapath** [comment]
> > @serapath
i perceive two solidity files with the same imported content, but different imported file names to be the same.
* `/user/serapath/solidity/foo.sol` with importing `/user/serapath/solidity/bar.sol`
* to be the exact same source code as `/user/chriseth/solidity/foo.sol` importing `/user/christeth/solidity/bar.sol`
but as i understand - currently the scenario i just described would produce different bytecode, just because you copied my solidity files and compile it from your file system with slightly different paths...
i would rather see those two scenarios produce the exact same bytecode
* where everything starts with `index.sol` (or `main.sol`)
* and then the import of `bar.sol` requires a resolver to find  `<hash-of-"bar.sol"-content>.sol`

so you on your machine and i on my machine compiling the same source code would work exactly the same ...
or not?
how would you want it to work?

-------

**Comment by serapath** [comment]
* v2240gjwspgj4j94w
    * contract.sol
        ```
        import 42j490gj294jg2094jg9w0jg4 // Baz
        import v2240gjwspgj4j94w  // Baz
        contract Foo { ... }
        ```
    * metadata.json
* 42j490gj294jg2094jg9w0jg4
    * contract.sol
        ```
        import v2240gjwspgj4j94w // Baz
        contract Baz { ... }
        ```
    * metadata.json
* v2240gjwspgj4j94w
    * contract.sol
        ```
        import 79g79g79f8f6j6f // Quux
        contract Baz { ... }
        ```
    * metadata.json
* 79g79g79f8f6j6f
    * contract.sol
        ```
        contract Quux{ ... }
        ```
    * metadata.json

**Comment by alincode** [comment]
![螢幕快照 2019-07-02 下午11 10 37](https://user-images.githubusercontent.com/7610755/60524158-a38cbc80-9d1e-11e9-8118-fb2a73455ba2.png)

**Comment by alincode** [comment]
![螢幕快照 2019-07-02 下午11 21 15](https://user-images.githubusercontent.com/7610755/60525037-3c700780-9d20-11e9-8495-881d5e25104a.png)

**Comment by serapath** [comment]
lovely :heart: :smile:

**Comment by serapath** [comment]
oh, i updated... small changes. @alincode 
Let's try to structure it like:

* `<source-hash-folder-name>/`
    * `source.sol`
        ```
        contract MyContract { ... }
        ```
    * `contract/`
        * `<deployed-address-of-MyContract-Instance-1.json`
        * `<deployed-address-of-MyContract-Instance-2.json`
        * `<deployed-address-of-MyContract-Instance-3.json`

Check my updated comment above https://github.com/ethereum-play/etherscan-scraper/issues/2#issuecomment-507711514 for a more detailed example :-)
