### ISSUE TITLE
process all stored source codes into the correct format

### ISSUE THREAD

**Issue by serapath** [ethereum-play/etherscan-scraper#4]
## `@todo:`
* [ ] split source files with more than one contract into multiple files and add import statements
* [ ] [#143 AST import analysis and hashing](https://github.com/ethereum/play/issues/143)
* [ ] use [solidity AST analyser for imports hashing](https://github.com/ethereum/play/issues/143) to re-write all contract data into the correct format

---
**problem1**
A lot of contracts might contain more than one contract definition and they need to be split into multiple files, each with only a single contract definition. In the end they are re-added my adding the correct import statements, so that the result works in the same way than the single file with multiple contract definitions

**problem2**
Two people can compile and deploy the same contract.
1. `/user/serapath/solidity/foo.sol` with importing `/user/serapath/solidity/bar.sol`
2. `/user/chriseth/solidity/foo.sol` importing `/user/christeth/solidity/bar.sol`

The compiler will output two different bytecode hashes, so it is hard to verify the contract if you only have the source code, but don't know what was the filepath from which it was compiled.

**correct format (example)**
* `sourcecode/xx240gjwspgj4j95K/` (=hash of `source.sol` where all imports are hash names)
    * `source.sol`
        ```
        import 42j490gj294jg2094jg9w0jg4 // Bar
        import v2240gjwspgj4j94w  // Baz
        contract Foo { ... }
        ```
    * `contract/`
        * `0x457dsaf704e39fc728058557a113b226207d2212.json` (= deployed address of Foo instance)
            ```js
            {
              // @TODO: think and discuss what other information to store here
              // * compiler version
              // * compiler flags
              // * ...
              "filepath": "~/Desktop/Foo.sol",
              "imports": {
                "xx240gjwspgj4j95K": { // FOO
                  "42j490gj294jg2094jg9w0jg4": "~/Desktop/Bar.sol",
                  "v2240gjwspgj4j94w": "/user/johndoe/Desktop/modules/Baz.sol"
                },
                "42j490gj294jg2094jg9w0jg4": { // BAR
                  "v2240gjwspgj4j94w": "./modules/Baz.sol",
                },
                "v2240gjwspgj4j94w": { // BAZ
                  "79g79g79f8f6j6f ": "~/mycontracts/quux.sol",
                }
                "79g79g79f8f6j6f": { // QUUX
                  "42j490gj294jg2094jg9w0jg4": "../Desktop/Bar.sol",
                }
              }
            }
            ```
        * `0xnv7d56704e39fc728058557a113b226207d2212.json` (= another deployed address of Foo instance)
            ```js
            {
              "filepath": "/user/johnny5/contracts/Foo.sol",
              "imports": {
                "xx240gjwspgj4j95K": { // FOO
                  "42j490gj294jg2094jg9w0jg4": "/user/johnny5/contracts/Bar.sol",
                  "v2240gjwspgj4j94w": "/user/johnny5/contracts/Baz.sol"
                },
                "42j490gj294jg2094jg9w0jg4": { // BAR
                  "v2240gjwspgj4j94w": "/user/johnny5/contracts/Baz.sol",
                },
                "v2240gjwspgj4j94w": { // BAZ
                  "79g79g79f8f6j6f ": "/user/johnny5/contracts/quux.sol",
                }
                "79g79g79f8f6j6f": { // QUUX
                  "42j490gj294jg2094jg9w0jg4": "/user/johnny5/contracts/Bar.sol",
                }
              }
            }
            ```
* `sourcecode/42j490gj294jg2094jg9w0jg4/`
    * `source.sol`
        ```
        import v2240gjwspgj4j94w // Baz
        contract Bar { ... }
        ```
    * `contract/`
* `sourcecode/v2240gjwspgj4j94w/`
    * `source.sol`
        ```
        import 79g79g79f8f6j6f // Quux
        contract Baz { ... }
        ```
    * `contract/`
* `sourcecode/79g79g79f8f6j6f/`
    * `source.sol`
        ```
        import 42j490gj294jg2094jg9w0jg4 // Bar
        contract Quux{ ... }
        ```
    * `contract/`
        * `0xd556caf704e39fc728058557a113b226207d2212.json`
            ```js
              // ... see above examples ...
            ```
        * `0xa64sscaf704e39fc728058557a113b226207d2212.json`
            ```js
              // ... see above examples ...
            ```
