### ISSUE TITLE
update scraper

### ISSUE THREAD

**Issue by serapath** [ethereum-play/etherscan-scraper#6]
## `@todo`
* [x] Run the scraper locally and make sure it runs and stores all contracts
* [x] Write a tutorial how to use the updated github scraper repository and publish and run it on digital ocean
* [x] Run scraper server on digital ocean droplet and make sure it keeps on running
* [x] replace mySQL with filesystem and store all smart contract source codes in `sourcecodes/`
* [x] create REST API server with routes to check:
    1. how much space the `sourcecodes/**/*` folder is using
    2. how many contracts are stored in total (maybe: https://stackoverflow.com/a/22957193)
    3. respond with the result of `ls ./sourcecodes`
* [x] **share/publish scraped data**
    * [x] `dat share` the folder of stored contracts using the the **[dat cli](https://www.npmjs.com/package/dat)**
* [x] [#8 scraper until presentation](https://github.com/ethereum-play/etherscan-scraper/issues/8)
* [ ] add more information and metadata to the scraped source codes inspired by here:
    * https://github.com/blockscout/evm-smart-contracts/blob/master/contracts/1/0x0000000000075efbee23fe2de1bd0b7690883cc9.json
* [ ] check that scraper is continues to run (it should scrape many thousands of contracts but currently has only around 900-1000 contracts), which is too little
* [ ] once all content has been scraped from etherscan, try adding a new one to etherscan and see if the scraper receives the updates - if not, make it work :-)
* [ ] [#7 handle fetching an always up-to-date list of proxy servers](https://github.com/ethereum-play/etherscan-scraper/issues/7)
* [ ] add additional API to server `/dat` to tell if `dat share ...` is still serving
    * if so it should `curl https://<digitaloceanserver ip>/dat` returns e.g. `true`
* [ ] also http://104.248.146.46:3001/list has a broken formatting and the output seems to be formatted with HTML but it woud be better to have raw text with no HTML tags at all
* [ ] also can you change the README.MD and delete the old content in it and instead write the scraper server address and document the API? :-)
    * `http://104.248.146.46:3001`
        * **/dat** - indicates `true` or `false` to tell whether dat is still active or not
        * **/daturl** - returns the `dat://<address>` which can be used to download all contract
        * **/count** - gives the total amount of contracts currently stored on the server
        * **/size** - shows how much disk space contracts occupy
        * **/list** - shows a list of all contracts on the server
* [ ] write a tutorial (with screencast) how to update the digital ocean droplet with that changed code and keep it running
* [ ] scrape source codes manually from URLs below to add them to the database once
    * [ ] https://github.com/blockscout/evm-smart-contracts
    * [ ] contact @serapath for some additional sources to scrape
* [ ] [#9 verify source code](https://github.com/ethereum-play/etherscan-scraper/issues/9)
* [ ] [#4 process all stored source codes into the correct format](https://github.com/ethereum-play/etherscan-scraper/issues/4)
    * [ ] start with a small subset of contracts (...maybe 20 contracts)
    * [ ] create a modified `verifier` module to still be able to verify them
    * [ ] process all contracts and verify them once the small subset of 20 works and can be verified
* [ ] [#5 store all smart contract source codes in dat and publish on DHT](https://github.com/ethereum-play/etherscan-scraper/issues/5)
    * [ ] test success by loading the published dat address in [beaker browser]
(https://beakerbrowser.com/)
* [ ] make a repository for a pure dat based p2p database node which can run on DappNode
    * https://twitter.com/thegrifft/status/1160220722947510272

---
